### ISSUE TITLE
Is there an STL file for the AUX sensor case?

### ISSUE THREAD

**Issue by hnktn** [Shine-Bright-Meow/SlimeVR-Hyperion-BMI-BNO-PCB-Case#1]
Hello,

I am interested in obtaining the STL file for the AUX sensor case. Does the repository contain the 3D model file for the case used with the AUX sensor? If so, could you please provide a link to download it? 

Thank you in advance for your assistance.

**Comment by ShineBrightMeow** [comment]
Hi Hnktn, I don't have an AUX case. There are several decent ones out there already. Check out: <https://github.com/Lixulia/Arcturus> and <https://www.printables.com/model/647109-minted-arcturus-slimevr-diy-standard-parts/files>

**Comment by hnktn** [comment]
Hi ShineBrightMeow,

Thank you for your response and the provided links. I appreciate your help. I will check out the resources you shared to find an AUX case that suits my needs.
